feature-server:
  enabled: true


transformation-service:
  enabled: true

redis:
  enabled: true
  usePassword: false

global:
  registry:
    # S3 bucket path to store registry.db
    path: s3://nsa2-sf-ml-models/feast/registry/registry.db
    #path: gs://path/to/registry.db
    cache_ttl_seconds: 0

  # global.project -- Project from feature_store.yaml
  project: default