feature_store_yaml_base64: "cHJvamVjdDogbWxvcHMKCnJlZ2lzdHJ5OgogIHJlZ2lzdHJ5X3R5cGU6IHNxbAogIHBhdGg6IHBvc3RncmVzcWwrcHN5Y29wZzovLyR7UE9TVEdSRVNRTF9VU0VSTkFNRX06JHtQT1NUR1JFU1FMX1BBU1NXT1JEfUAke1BPU1RHUkVTUUxfSE9TVH06JHtQT1NUR1JFU1FMX1BPUlR9LyR7UE9TVEdSRVNRTF9EQVRBQkFTRX0KCm9ubGluZV9zdG9yZToKICB0eXBlOiByZWRpcwogIGNvbm5lY3Rpb25fc3RyaW5nOiAicmVkaXM6Ly86JHtSRURJU19QQVNTV09SRH1AJHtSRURJU19IT1NUfToke1JFRElTX1BPUlR9LyR7UkVESVNfREJ9Ig==
"

extraEnvs:
  - name: "POSTGRESQL_USERNAME"
    value: "admin"
  - name: "POSTGRESQL_HOST"
    value: "postgresql.service-foundry.svc.cluster.local"
  - name: "POSTGRESQL_PORT"
    value: "5432"
  - name: "POSTGRESQL_DATABASE"
    value: "feast"
  - name: "REDIS_HOST"
    value: "redis-master.service-foundry.svc.cluster.local"
  - name: "REDIS_PORT"
    value: "6379"
  - name: "REDIS_DB"
    value: "0"
  - name: "POSTGRESQL_PASSWORD"
    valueFrom: 
      secretKeyRef:
        name: feast-secret
        key: POSTGRESQL_PASSWORD
  - name: "REDIS_PASSWORD"
    valueFrom: 
      secretKeyRef:
        name: feast-secret
        key: REDIS_PASSWORD

