kind: ConfigMap
apiVersion: v1
metadata:
  name: feast-configmap
data:
  POSTGRESQL_USERNAME: admin
  POSTGRESQL_HOST: postgresql.service-foundry.svc.cluster.local
  POSTGRESQL_PORT: 5432
  POSTGRESQL_DATABASE: feast
  REDIS_HOST: redis-master.service-foundry.svc.cluster.local
  REDIS_PORT: 6379
  REDIS_DB: 0 