
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - service-foundry-license-keys-dev-sealed.yaml


helmGlobals:
  chartHome: ../chart-home

helmCharts:
  - name: service-foundry-community
    releaseName: service-foundry-community
    namespace: dev
    valuesFile: values-dev.yaml