apiVersion: v1
kind: Pod
metadata:
  name: longhorn-rwx-debug
  namespace: service-foundry
spec:
  containers:
  - name: longhorn-rwx-debug
    image: busybox
    command: ["sh", "-c", "sleep 36000"]
    restartPolicy: Never
    volumeMounts:
    - mountPath: /data
      name: vol
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: custom-node-exporter-logs-pvc