ingressRoute:
  dashboard:
    # -- Create an IngressRoute for the dashboard
    enabled: true

  healthcheck:
    # -- Create an IngressRoute for the healthcheck
    enabled: true

env:
  - name: USER
    value: "traefik"

# 639
#ports:
#  traefik:
#    nodePort: 31080
#    expose:
#      default: true
#  web:
#    nodePort: 30080
#
#  websecure:
#    nodePort: 30443

ports:
#  web:
#    port: 80
#    nodePort: 30080
#    forwardedHeaders:
#      insecure: true

  websecure:
#    port: 443
#    nodePort: 30443
    targetPort: web
    proxyProtocol:
      insecure: true
    forwardedHeaders:
      insecure: true


logs:
  general:
    level: TRACE

service:
  type: LoadBalancer  # default is LoadBalancer
#  type: NodePort
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:ca-central-1:445567090745:certificate/c1e0e297-2ac5-4bf2-a437-8282d3dcfe65"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    #service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" # alb or nlb
    #service.beta.kubernetes.io/aws-load-balancer-type: "external"
#  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
#    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:ca-central-1:445567090745:certificate/7e16dc28-274a-41a0-a197-9a2eaebae07a"
#    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
#    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
#    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "http"
#    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "31080"
#    service.beta.kubernetes.io/aws-load-balancer-healthcheck-pat: "/ping"

