
# 30
serviceAccount:
  create: false
  name: aws-load-balancer-controller

# 125
clusterName: nsa2-sf

# If you’re deploying the controller to Amazon EC2 nodes
# that have restricted access to the Amazon EC2 instance metadata service (IMDS),
# or if you’re deploying to Fargate or Amazon EKS Hybrid Nodes,
# then add the following flags to the helm command that follows:

# 165
#region: ca-central-1
# 168
#vpcId: vpc-00d968cd350b6b1fa


