apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: airflow-environments
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: dev
        namespace: airflow-dev
      # Uncomment when you create staging and prod overlays
      # - env: staging
      #   namespace: airflow-staging
      # - env: prod
      #   namespace: airflow-prod
  
  template:
    metadata:
      name: 'airflow-{{env}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      
      source:
        # Update this with your Git repository URL
        repoURL: https://github.com/nsalexamy/service-foundry.git
        targetRevision: main
        path: 'documents/blog/kustomize-helm-chart/airflow-gitops/{{env}}'
        
        kustomize:
          # REQUIRED: Enable Helm chart inflation
          buildOptions: "--enable-helm"
      
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        
        syncOptions:
          - CreateNamespace=true
        
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
