global:
  version: 0.2.0

host: community-dev.servicefoundry.org

frontend:

  config:
    enabled: true
    # Default config.json content for the React app (will be put into a ConfigMap)
    content: |
      {
        "backendServer": "https://community-dev.servicefoundry.org/api",
        "appVersion": "0.14.0",
        "builderVersion": "0.14.0",
      }