apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Staging</title>
    </head>
    <body>
        <h1>Staging Page</h1>
    </body>
    </html>