kserve:
  controller:
    deploymentMode: Standard
    gateway:
      #domain: kserve.servicefoundry.org
      domain: servicefoundry.org
      # default is http
      urlScheme: https
      ingressGateway:
        enableGatewayApi: true
        #kserveGateway=kserve/kserve-ingress-gateway
        kserveGateway: traefik/traefik-gateway
        className: traefik


  storage:
    storageSpecSecretName: mlops-aws-credentials
    s3:
      # s3://nsa2-sf-ml-models/mlflow/2/models/m-2551ab2217244663b227f8e5d9dadbe3/artifacts/model.pkl
      endpoint: s3.ca-central-1.amazonaws.com
      region: ca-central-1
      useHttps: "1"
      verifySSL: "1"
      useVirtualBucket: "1"
      useAnonymousCredential: "0"