apiVersion: v1
kind: Service
metadata:
  name: kserve-controller-manager-service
  namespace: 
  labels:
    control-plane: kserve-controller-manager
    controller-tools.k8s.io: "1.0"
  annotations: 
spec:
  selector:
    control-plane: kserve-controller-manager
    controller-tools.k8s.io: "1.0"
  ports:
  - port: 8443
    targetPort: https
    protocol: TCP
