apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: inferenceservice.serving.kserve.io
  annotations:
    cert-manager.io/inject-ca-from: /serving-cert
webhooks:
  - clientConfig:
      service:
        name: kserve-webhook-server-service
        namespace: 
        path: /validate-serving-kserve-io-v1beta1-inferenceservice
    failurePolicy: Fail
    name: inferenceservice.kserve-webhook-server.validator
    sideEffects: None
    admissionReviewVersions: ["v1beta1"]
    rules:
      - apiGroups:
          - serving.kserve.io
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - inferenceservices

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: trainedmodel.serving.kserve.io
  annotations:
    cert-manager.io/inject-ca-from: /serving-cert
webhooks:
  - clientConfig:
      service:
        name: kserve-webhook-server-service
        namespace: 
        path: /validate-serving-kserve-io-v1alpha1-trainedmodel
    failurePolicy: Fail
    name: trainedmodel.kserve-webhook-server.validator
    sideEffects: None
    admissionReviewVersions: ["v1beta1"]
    rules:
      - apiGroups:
          - serving.kserve.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - trainedmodels

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: inferencegraph.serving.kserve.io
  annotations:
    cert-manager.io/inject-ca-from: /serving-cert
webhooks:
  - clientConfig:
      service:
        name: kserve-webhook-server-service
        namespace: 
        path: /validate-serving-kserve-io-v1alpha1-inferencegraph
    failurePolicy: Fail
    name: inferencegraph.kserve-webhook-server.validator
    sideEffects: None
    admissionReviewVersions: ["v1beta1"]
    rules:
      - apiGroups:
          - serving.kserve.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - inferencegraphs
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: clusterservingruntime.serving.kserve.io
  annotations:
    cert-manager.io/inject-ca-from: /serving-cert
webhooks:
  - clientConfig:
      service:
        name: kserve-webhook-server-service
        namespace: 
        path: /validate-serving-kserve-io-v1alpha1-clusterservingruntime
    failurePolicy: Fail
    name: clusterservingruntime.kserve-webhook-server.validator
    sideEffects: None
    admissionReviewVersions: ["v1beta1"]
    rules:
      - apiGroups:
          - serving.kserve.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - clusterservingruntimes
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: servingruntime.serving.kserve.io
  annotations:
    cert-manager.io/inject-ca-from: /serving-cert
webhooks:
  - clientConfig:
      service:
        name: kserve-webhook-server-service
        namespace: 
        path: /validate-serving-kserve-io-v1alpha1-servingruntime
    failurePolicy: Fail
    name: servingruntime.kserve-webhook-server.validator
    sideEffects: None
    admissionReviewVersions: ["v1beta1"]
    rules:
      - apiGroups:
          - serving.kserve.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - servingruntimes
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: localmodelcache.serving.kserve.io
  annotations:
    cert-manager.io/inject-ca-from: /serving-cert
webhooks:
  - clientConfig:
      service:
        name: kserve-webhook-server-service
        namespace: 
        path: /validate-serving-kserve-io-v1alpha1-localmodelcache
    failurePolicy: Fail
    name: localmodelcache.kserve-webhook-server.validator
    sideEffects: None
    admissionReviewVersions: ["v1beta1"]
    rules:
      - apiGroups:
          - serving.kserve.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - localmodelcaches
