{{- if .Values.licenseSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.licenseSecret.name }}
type: Opaque
stringData:
  {{ .Values.licenseSecret.key }}: |
{{ .Values.licenseSecret.privateKey | indent 4 }}
{{- end }}

