apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airflow-dev

resources:
  - ../base
  # - namespace.yaml
  - airflow-postgresql-credentials-secret.yaml
  - airflow-webserver-default-user-credentials.yaml
#  - keycloak-admin-secret.yaml
#  - keycloak-db-secret.yaml

helmCharts:
  - name: airflow
    repo: https://airflow.apache.org
    version: 1.18.0
    releaseName: airflow
    namespace: airflow-dev
    valuesFile: values-dev.yaml